"""add indexes for avaliacoes

Revision ID: 06f836d2e677
Revises: 2e7815c327d0
Create Date: 2026-04-12 00:46:41.779155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06f836d2e677'
down_revision: Union[str, None] = '2e7815c327d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_avaliacoes_pedidos_id_pedido'), 'avaliacoes_pedidos', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_itens_pedidos_id_produto'), 'itens_pedidos', ['id_produto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedidos_id_produto'), table_name='itens_pedidos')
    op.drop_index(op.f('ix_avaliacoes_pedidos_id_pedido'), table_name='avaliacoes_pedidos')
    # ### end Alembic commands ###
