"""Add resposta admin to avaliacoes

Revision ID: 2e7815c327d0
Revises: b0d89c19605d
Create Date: 2026-04-11 23:41:44.844895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e7815c327d0'
down_revision: Union[str, None] = 'b0d89c19605d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avaliacoes_pedidos', sa.Column('resposta_admin', sa.Text(), nullable=True))
    op.add_column('avaliacoes_pedidos', sa.Column('autor_resposta', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avaliacoes_pedidos', 'autor_resposta')
    op.drop_column('avaliacoes_pedidos', 'resposta_admin')
    # ### end Alembic commands ###
